{
    'name': 'Tritunggal Logistik',
    'version': '1.0',
    'category': 'Logistics/ERP',
    'summary': 'Modul logistik untuk CV Tritunggal Transportindo',
    'depends': ['base', 'hr', 'portal', 'website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'report/invoice_report.xml',
        'views/pesanan_views.xml',
        'views/item_pesanan_views.xml',
        'views/res_partner_views.xml',
        'views/pengiriman_views.xml',
        'views/penugasan_pengiriman_views.xml',
        'views/armada_views.xml',
        'views/laporan_kerusakan_views.xml',
        'views/riwayat_perawatan_views.xml',
        'views/invoice_views.xml',
        'views/menu_views.xml',
        'views/portal_templates.xml',
        'views/website_branding.xml',
        'data/users.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
}
